import { database, initDatabase } from "./database";
export interface Collection { id:string; name:string; parentId:string|null; createdAt:number; updatedAt:number; documentCount:number }
const id=()=>`col_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
export async function getCollections(parentId:string|null=null){ await initDatabase(); const d=await database(); return d.getAllAsync<Collection>(`SELECT c.id,c.name,c.parent_id as parentId,c.created_at as createdAt,c.updated_at as updatedAt,COUNT(cd.document_uri) as documentCount FROM collections c LEFT JOIN collection_documents cd ON cd.collection_id=c.id WHERE ${parentId===null?"c.parent_id IS NULL":"c.parent_id = ?"} GROUP BY c.id ORDER BY c.name COLLATE NOCASE`,...(parentId===null?[]:[parentId])); }
export async function createCollection(name:string,parentId:string|null=null){ const clean=name.trim(); if(!clean) throw new Error("Collection name is required"); await initDatabase(); const d=await database(); const now=Date.now(),collectionId=id(); await d.runAsync("INSERT INTO collections(id,name,parent_id,created_at,updated_at) VALUES(?,?,?,?,?)",collectionId,clean,parentId,now,now); return collectionId; }
export async function renameCollection(collectionId:string,name:string){ const clean=name.trim(); if(!clean) throw new Error("Collection name is required"); const d=await database(); await d.runAsync("UPDATE collections SET name=?,updated_at=? WHERE id=?",clean,Date.now(),collectionId); }
export async function deleteCollection(collectionId:string){ const d=await database(); await d.runAsync("DELETE FROM collections WHERE id=?",collectionId); }
export async function addDocumentToCollection(collectionId:string,documentUri:string){ const d=await database(); await d.runAsync("INSERT OR IGNORE INTO collection_documents(collection_id,document_uri,added_at) VALUES(?,?,?)",collectionId,documentUri,Date.now()); }
export async function removeDocumentFromCollection(collectionId:string,documentUri:string){ const d=await database(); await d.runAsync("DELETE FROM collection_documents WHERE collection_id=? AND document_uri=?",collectionId,documentUri); }
export async function getCollectionDocumentUris(collectionId:string){ const d=await database(); const rows=await d.getAllAsync<{documentUri:string}>("SELECT document_uri as documentUri FROM collection_documents WHERE collection_id=?",collectionId); return rows.map(x=>x.documentUri); }
